authorName: hangdtt
experimentName: search_in_one64th
trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python train.py -cuda 0 -e 23 
  codeDir: ../
  gpuNum: 1
localConfig:
  useActiveGpu: True